### ISSUE TITLE
Disable the extension on wordpress admin panel

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#105]
Apparently having the extension sending GET requests when hovering a button triggers action in wordpress and can lead to the deletion of some articles for example.

**Comment by rezziemaven** [comment]
Hey @mdolr! So just to clarify, you're saying that if a user who has the extension enabled in the browser and is in the admin panel of their own WordPress site, it can accidentally delete articles/ posts from their site?

**Comment by mdolr** [comment]
Exactly, if the user hovers an action the extension will send a GET request to the link behind the button and from what I understand wordpress uses GET requests for its API so the extension should be disabled on any wordpress admin panel

**Comment by rezziemaven** [comment]
Awesome, thanks for clarifying! I'd love to work on this; can you assign it to me?

**Comment by mdolr** [comment]
Hello @rezziemaven you've asked me to assign this issue aswell as #96 3 days ago, have you had time to work on those ? If not do you still plan to work on them ?

**Comment by rezziemaven** [comment]
Hey @mdolr, I haven’t had the time to work on either of them but yes, I still plan to work on both of them. I’ll have more time to work on it this weekend. I hope that’s okay with you.
