### ISSUE TITLE
Feature request: Inject in existing web pages

### ISSUE THREAD

**Issue by niutech** [mdolr/survol#144]
Once upon a time there was a great project [Snap Shots](https://web.archive.org/web/20111002235808/http://www.snap.com/snapshots.php), which added external links previews on hover to any web page by injecting a special `<script>`. There were many of previews to choose from (see [Menu of Shots](https://web.archive.org/web/20111002235808/http://www.snap.com/snapshots.php#menu)). Please provide a similar script along with browser extensions, so that web devs could enable this functionality for their own web pages.

**Comment by mdolr** [comment]
Duplicate. See #82
