### ISSUE TITLE
Clean twitter CSS

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#16]
Currently tweets are not looking good, the goal is to find a way to make them look like real embed tweets provided by [Twitter publisher](https://publish.twitter.com). 

We can't use the script provided by twitter as it doesn't work as a content script and I'm waiting currently waiting for an answer [from Twitter dev forum](https://twittercommunity.com/t/twitter-widget-not-working-as-content-script/130526)
Because the script doesn't work we can't use createTweet or even load.

**Comment by iFonny** [comment]
hello

**Comment by mdolr** [comment]
Closed with #19
