### ISSUE TITLE
Clean reddit post CSS

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#17]
Currently posts are not looking good, the goal is to find a way to make them look like real embed tweets provided by reddit embed code (i.e embedly). As with twitter we can't use the script provided by embedly as it doesn't work as an content script so we're not able to generate embeds or load them.

**Comment by rohithjayaraman** [comment]
This is gonna be my first issue. Mind if I give it a shot ?

**Comment by mdolr** [comment]
yes go on good luck, I'll assign this one to you then

**Comment by rohith-jayaraman** [comment]
Okay so how exactly does the extension work ? As in when does it show me the preview. Do I need to hover over the link or ? I have cloned the repo and added the extension

**Comment by mdolr** [comment]
Yes you have to hover the link, you should find a test page at `html/test.html` with every working platform / type of link

**Comment by iFonny** [comment]
hello

**Comment by hisakiyo** [comment]
> hello

slt ifo

**Comment by rohith-jayaraman** [comment]
Have you considered having seperate blocks for comments and posts ?

**Comment by mdolr** [comment]
what do you mean ?

**Comment by rohith-jayaraman** [comment]
Nothing nothing. stupid question. forget it. sorry

**Comment by rohith-jayaraman** [comment]
Hey do you want it to look like what you have done for the reddit comment ?

**Comment by mdolr** [comment]
Yes that's the idea I guess ? If you've something better go for it

**Comment by rohith-jayaraman** [comment]
Is it okay if I use a black icon instead of the orange one ? I think there are IPR issues with the orange since this isn't official reddit stuff

**Comment by mdolr** [comment]
We're embedding reddit content I believe there should be no problem using the reddit icon as its their content? If their normal card were working we would be using those, and those cards would have official reddit branding

**Comment by rohith-jayaraman** [comment]
I am almost done. Should be raising a PR in a few hours.

**Comment by rohithjayaraman** [comment]
Are you happy with it or you want some changes ?

**Comment by mdolr** [comment]
The issue is closed and I merged your PR, I still did some minor changes but it was good overall.

**Comment by rohithjayaraman** [comment]
I know. I saw that you made a few changes and closed it. Just wanted to check if you needed anything else. It was really nice working on your repo. Thanks for the opportunity 😁

**Comment by mdolr** [comment]
Thank you for your contribution!
