### ISSUE TITLE
CSS : When using the extension on reddit, embeds are being hidden when goign out of the parent

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#26]
Here is an example, the embed gets cropped, in a normal scenario we should be able to see the red part : 
![image](https://user-images.githubusercontent.com/19026937/66706152-b5bfc300-ed2f-11e9-97c0-7ba9f7422c5b.png)

It happens on both old.reddit.com and reddit.com

**Comment by cjscheller** [comment]
@mdolr Submitted PR #31 intended to resolve this issue.

**Comment by mdolr** [comment]
Solved with #33
