### ISSUE TITLE
Reddit integration : Add date to the footer

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#27]
Date should be displayed like on reddit, "Submitted X hours/days ago by u/username"
Also if you could rework the post data in the footer a bit :+1:

**Comment by grufkork** [comment]
I'll take a look at this!

**Comment by mdolr** [comment]
I think the postData object has a timestamp variable to help you with that

**Comment by grufkork** [comment]
I will reformat the footer a bit. Maybe a different font would look better?

**Comment by mdolr** [comment]
I think we should keep embeds coherent if you want to change the font use the one used in the twitter embed. 
When I was talking about the footer it was more about moving the post score and comments inline or something like that. Finding a good placement for each information

**Comment by grufkork** [comment]
Font looked good enough, so I didn't change. But maybe do an extension-wide font change in the future? Neat extension by the way!

**Comment by mdolr** [comment]
We will discuss font change once we have a defined style, I'm closing this with #28
