### ISSUE TITLE
Parse hashtags in tweets

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#35]
Right now, tweets are displayed as texts and hashtags appear like that : {tweet text} <a href=...>{Hashtag}</a> {tweet...}. 
The goal of this is issue is to parse hashtags in a tweet to display them just like on twitter {tweet text} #{hashtag} {tweet...}

**Comment by jsilvaigor** [comment]
Hi, I'll fix a look on this one

**Comment by mdolr** [comment]
I think it is already being worked on there have been 2 forks since the creation of this issue :/ 
Maybe you can work on integrating profiles ?

**Comment by jsilvaigor** [comment]
I've take a look on the other issues and didn't found the one you mentioned, which one it's?

**Comment by mdolr** [comment]
This issue is fixed with #36 
I opened #37 if you want then
