### ISSUE TITLE
Reddit integration

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#4]
Integration of reddit.com
- Preview comments (done)
- Preview posts

Using reddit's embed code

**Comment by mdolr** [comment]
Help on integrating posts would be appreciated !

**Comment by joshuatz** [comment]
@mdolr I can submit something for this shortly; I took a quick pass at implementing it and got it working, just need to clean up my code and then I can make a PR.

![reddit-post-integration](https://user-images.githubusercontent.com/17817563/66277856-e481f900-e858-11e9-88f5-e5688045c75c.gif)

**Comment by mdolr** [comment]
Closed with #14
