### ISSUE TITLE
Create an extension settings page (settings: disable extension on this page)

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#40]
Create a little page which opens when clicking on the extension icon to disable the extension on the current website
Make sure we can add other options later like changing the language, or even switch other settings in the extension

**Comment by Coteh** [comment]
Sorry, just discovered this project a few minutes ago, is there functionality currently implemented (e.g. a flag) that effectively disables functionality of the extension, or does that need to be added for this issue as well?

I'm interested in taking this.

**Comment by mdolr** [comment]
Hey there isn't, it should be added with the little settings page
