### ISSUE TITLE
Content appears twice when moving mouse too fast

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#42]
When you hover a link too fast sometimes 2 elements are appended to the survol div instead of just 1

**Comment by Coteh** [comment]
I'm interested in taking this.

**Comment by mdolr** [comment]
I finally figured it out, this happens because the div waits for the request to end to add the content, and the mouseleave event is triggered while the div is empty (so nothing is cleared), when the content is finally loaded your cursor has already entered another a href

**Comment by Coteh** [comment]
Ah interesting! I wonder if we could somehow cancel the request when mouseleave event is triggered while there's a pending request. Or perhaps we can discard the result when it comes back if we're unable to do that.

**Comment by mdolr** [comment]
The referenced commit fixed the bug when going from one node to another, but apparently the bug can happen when staying on the same node ?
