### ISSUE TITLE
Fix reddit post link parsing

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#46]
If the link ends with a / it is detected as a post, but if the final / is missing the link won't embed.
Example:  
* [Should work but doesn't](https://old.reddit.com/r/outrun/comments/ddj5cl/outatime)
* [Works fine](https://old.reddit.com/r/outrun/comments/ddj5cl/outatime/)

**Comment by Brett78** [comment]
Hey I took a crack at this, I hope you don't mind: https://github.com/mdolr/survol/pull/47

**Comment by mdolr** [comment]
Fixed in #47
