### ISSUE TITLE
Build a landing page to showcase the extension

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#5]
Build a simple and clean landing page (hosted through gh-pages) to showcase the extension

**Comment by pengyuejiang** [comment]
Hello! I am a participant of Hacktoberfest, and I'm interested in this task. Do you want a new file for the landing page, or simply edit the test.html?

**Comment by mdolr** [comment]
Hello ! test.html has nothing to do with that and is only used to quickly test the extension internally.
When thinking of a landing page I was thinking of a single landing page that would be hosted through Github Pages (example: https://onepagelove.com/runlet (the first thing I found on google that showcased what I thought of)). 

I'd suggest creating a folder "gh-pages" in which you put everything related to that landing page.

It should contain a title, some examples of the extension working
And maybe some links to preview when you have the extension, a place where to put download link for different browsers, a reference to the github ?

**Comment by pengyuejiang** [comment]
OK, I see. So currently I have the extension in my browser installed, but I'm not sure how to use it yet. I will try to work on a prototype, I'm a beginner, so would you accept using some bit of bootstrap4?

**Comment by mdolr** [comment]
I'd prefer not using a css framework but if you really need one I'd suggest bulma CSS
You can find all the docs at : https://bulma.io/ (it is very very similar to bootstrap but the class names are more explicit)

**Comment by pengyuejiang** [comment]
Alright I see, how to actually use the extension though after I installed it?

**Comment by mdolr** [comment]
Hum when visiting the test.html page (that's the quickest way) and hovering the links you should be able to preview them without clicking on them. Else just by hovering a link to a youtube video / a reddit comment / a wikipedia page

**Comment by pengyuejiang** [comment]
Oh yes! It worked, except for the Tweet link

**Comment by mdolr** [comment]
Yes twitter is not yet implemented I'm having some trouble with the loading of tweets and I'm currently waiting for an answer from the Twitter dev forum https://twittercommunity.com/t/twitter-widget-not-working-as-content-script/130526
