### ISSUE TITLE
Change div position when near screen border

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#50]
Sometimes the div goes out of the screen because the a href is on the bottom or far right of the page.
In this case switch the div above the cursor instead of below or on the left of the cursor instead of the right

**Comment by david-webber** [comment]
Can I take a look at this one? I might not be able to do it until tomorrow though.

**Comment by mdolr** [comment]
It's fine don't worry.
Everything related to the div position is in `js/core.js` in `insertSurvolDiv` in the `mousemove` event, you might want to play with the offsets I guess
