### ISSUE TITLE
Add italian translation

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#66]
Hello,
The extension needs translation for different languages.

You can find the language code (or locale code) you should use [on this page](https://developer.chrome.com/webstore/i18n#localeTable)

### Steps :
* Create a `_locales/[language_code]` folder
* Create a `messages.json` file at `_locales/[language_code]/messages.json`
* Copy paste content from `_locales/en/messages.json`
* Translate the "message" part for each JSON object

**Comment by chiaramistro** [comment]
I can do it for the Italian language!
