### ISSUE TITLE
Add dutch translation

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#67]
Hello,
The extension needs translation for different languages.

You can find the language code (or locale code) you should use [on this page](https://developer.chrome.com/webstore/i18n#localeTable)

### Steps :
* Create a `_locales/[language_code]` folder
* Create a `messages.json` file at `_locales/[language_code]/messages.json`
* Copy paste content from `_locales/en/messages.json`
* Translate the "message" part for each JSON object

**Comment by cvandermeer** [comment]
@mdolr i have a branch ready but i do not have permission to push my branch

**Comment by mdolr** [comment]
You have to make a pull request, I recommend you watch some guides online on how to do that
