### ISSUE TITLE
Add chinese translation

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#69]
Hello,
The extension needs translation for different languages.

You can find the language code (or locale code) you should use [on this page](https://developer.chrome.com/webstore/i18n#localeTable)

### Steps :
* Create a `_locales/[language_code]` folder
* Create a `messages.json` file at `_locales/[language_code]/messages.json`
* Copy paste content from `_locales/en/messages.json`
* Translate the "message" part for each JSON object

**Comment by plushugh** [comment]
I'll do it, Chinese is my first language😀

Assign it to me so I can work on it.

**Comment by plushugh** [comment]
It's done! [My Repo](https://github.com/plushugh/survol)

**Comment by plushugh** [comment]
PR #75

**Comment by Hsins** [comment]
@mdolr There are Traditional Chinese and Simplified Chinese in the world. Would you mind to open another issue for "Add Traditional Chinese Translation" and assign it to me?

**Comment by mdolr** [comment]
@Hsins hey, just submit a pull request if you want to add a new language that is not in the issue list, let's not overcomplicate things :+1:.
