### ISSUE TITLE
Add korean translation

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#72]
Hello,
The extension needs translation for different languages.

You can find the language code (or locale code) you should use [on this page](https://developer.chrome.com/webstore/i18n#localeTable)

### Steps :
* Create a `_locales/[language_code]` folder
* Create a `messages.json` file at `_locales/[language_code]/messages.json`
* Copy paste content from `_locales/en/messages.json`
* Translate the "message" part for each JSON object

**Comment by NashilChoi** [comment]
Hi @mdolr , I can take a look into this if you like

**Comment by choinashil** [comment]
Hi @mdolr , I can take a look into this if you like

**Comment by mdolr** [comment]
Feel free to make a PR
