### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#73]
Add the possibility to switch the survol div to dark mode.

Tasks :
* Add a setting in the settings popup to toggle dark mode
* Change the CSS to have a dark mode maybe using css variables ?

**Comment by dmb1107** [comment]
Can you assign this to me so I can give it a go?

**Comment by KeshriAyushi22** [comment]
Hey can you assign this to me aswell, It will be a good learning for me

**Comment by mdolr** [comment]
Hum I’m confused, a PR has already been made ( #74 )

**Comment by KeshriAyushi22** [comment]
@mdolr sure, if any help required i would be happy to contribute

**Comment by mdolr** [comment]
Then I guess you should take a look at the PR :+1:

**Comment by KeshriAyushi22** [comment]
Hi,
Quick question, we need to make this extension a dark theme , using the
same toggle btn right?
[image: image.png]
*Thanks and Regards*
*Ayushi  Keshri*

**Comment by mdolr** [comment]
It should be applied when a switch in the popup window (settings when clicking on icon) is checked

**Comment by KeshriAyushi22** [comment]
![image](https://user-images.githubusercontent.com/49064703/95478233-e79d5100-09a6-11eb-9d3a-c1cca9840894.png)
@mdolr i will change the color scheme , just wanted to check whether  this is okay

**Comment by mdolr** [comment]
@dmb1107 @KeshriAyushi22 I've implemented a dark mode if you want to see how I've done it you can check the last commits. In the first commit I've started by unifying the CSS has there were some inconsistencies (fc5f5901b9cf88f7f1629b0a2f8851c8ab2b3c16).  

Then in the 2nd one I've implemented the dark mode (69cc54720fdc577d02fe7ae3531f265072fdf23c)
