### ISSUE TITLE
Extension icon + Color palette

### ISSUE THREAD

**Issue by mdolr** [mdolr/survol#9]
The project needs a graphic identity.
At least it needs an icon that can be clearly recognized so people can quickly change their options when needed without having to search for the extension for more than a minute if they have a lot of extensions already.

If you want to submit an icon it has to be compatible with the license (Apache 2.0) of the repository

**Comment by Swayamsvk** [comment]
Can I work on this?

**Comment by mdolr** [comment]
Of course, here is the style we're following for now (white background and rounded corners with a little box shadow)
![image](https://user-images.githubusercontent.com/19026937/66716912-8bbfdc80-edd3-11e9-85ed-19c818bdcc21.png)
![image](https://user-images.githubusercontent.com/19026937/66716934-ad20c880-edd3-11e9-887e-b6415bd062af.png)
